### ISSUE TITLE
Make Sounder compile on ARM

### ISSUE THREAD

**Issue by rdoosty** [renew-wireless/RENEWLab#32]
Add support for compilation and running of the sounder on ARM processors, e.g., on Raspberry Pi device.

**Comment by tingjunchen** [comment]
Adding the notes from our previous discussion here and maybe it's relevant:

- Rename `find_beacon_avx` to `find_beacon_avx2` and implement the `avx` version of `find_beacon`?
- Add support for ci16 formatting for client streaming?

**Comment by rdoosty** [comment]
Would you mind opening a separate issue for this?
