### ISSUE TITLE
Support Zadoff-chu pilots

### ISSUE THREAD

**Issue by rdoosty** [renew-wireless/RENEWLab#63]
Add support to use zadoff-chu based sequences as uplink pilots and channel analysis.

**Comment by mindy-min-zhang** [comment]
If --corr-thresh is unspecified in the command line or is set to 0.0, find_bad_nodes() will  not be called. Otherwise, i.e. if it is greater than 0, the function will be called and print the results on the terminal.

**Comment by mindy-min-zhang** [comment]
The support-pilot-types branch name is too long for Jenkins to trigger a build. Now created a new branch pilot-types which is branched off the latest support-pilot-types branch. Will create PR from the pilot-types branch to develop instead of the support-pilot-types branch.
