### ISSUE TITLE
Only allow full config with both BS and UE present

### ISSUE THREAD

**Issue by rdoosty** [renew-wireless/RENEWLab#96]

**Comment by tingjunchen** [comment]
We will also need to make sure that this works with uplink tests (for now if I run Sounder with only the BS config file, it doesn't run)... Thanks!

**Comment by rdoosty** [comment]
@tingjunchen Please try config-fix branch and let me know if that solves the issue: 

https://github.com/renew-wireless/RENEWLab/tree/config-fix
